// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBSGnH0TOATC7LgZNeFBvKdnlOne1naBrI',
    appId: '1:1016922861023:web:021092293f9345e340686a',
    messagingSenderId: '1016922861023',
    projectId: 'almacen-4ee70',
    authDomain: 'almacen-4ee70.firebaseapp.com',
    storageBucket: 'almacen-4ee70.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA7YDkmqrjX6idybjkn0mk_zZtepUoXey0',
    appId: '1:1016922861023:android:58223e14e1d3f84940686a',
    messagingSenderId: '1016922861023',
    projectId: 'almacen-4ee70',
    storageBucket: 'almacen-4ee70.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA0DMuZ8S5FD0WhEyGGzRRqQ08tnVrHEys',
    appId: '1:1016922861023:ios:90be5a888f93f87a40686a',
    messagingSenderId: '1016922861023',
    projectId: 'almacen-4ee70',
    storageBucket: 'almacen-4ee70.appspot.com',
    iosBundleId: 'com.example.almacen',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyA0DMuZ8S5FD0WhEyGGzRRqQ08tnVrHEys',
    appId: '1:1016922861023:ios:90be5a888f93f87a40686a',
    messagingSenderId: '1016922861023',
    projectId: 'almacen-4ee70',
    storageBucket: 'almacen-4ee70.appspot.com',
    iosBundleId: 'com.example.almacen',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBSGnH0TOATC7LgZNeFBvKdnlOne1naBrI',
    appId: '1:1016922861023:web:2cd569b1fdc0ecbe40686a',
    messagingSenderId: '1016922861023',
    projectId: 'almacen-4ee70',
    authDomain: 'almacen-4ee70.firebaseapp.com',
    storageBucket: 'almacen-4ee70.appspot.com',
  );

}